version: '3.7'

services:
    application:
        build: ./web
        command: gunicorn -c gunicorn_ini.py wsgi:app
        #command: python wsgi.py
        volumes:
            - ./web/:/usr/src/app/
        ports:
            - 5000:5000

    nginx:
        build:
            context: ./nginx
            args:
                DOMAIN: ${DOMAIN}
                FLASK: application
        ports:
            - 80:80
            - 443:443
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
        depends_on:
            - application

