version: '3.7'

services:
    web:
        build: ./web
        command: gunicorn --bind 0.0.0.0:5000 wsgi:app
        #command: python wsgi.py
        volumes:
            - ./web/:/usr/src/app/
        expose:
            - 5000


    nginx:
        build: ./nginx
        ports:
            - 80:80
        depends_on:
            - web

